### PR TITLE
Add Neo4j database

### PR DESCRIPTION
**Pull request by arif-hanif**
#50 
- Added Neo4j database
- Added some simple tests with snapshots using snapshooter

### CODE REVIEW

**Comment by michaelstaib** [comment]
@arif-hanif can you reformat the code to .NET style with braces on a new line?

**Comment by arif-hanif** [comment]
> @arif-hanif can you reformat the code to .NET style with braces on a new line?

yup i will get that fixed up I had a code formatter turned on VS Code

**Comment by arif-hanif** [comment]
@michaelstaib code formatting is fixed

**Comment by arif-hanif** [comment]
@bejto @michaelstaib Is this close to being approved?

**Comment by michaelstaib** [comment]
Should be

**Comment by arif-hanif** [comment]
@bejto could you sign the CLA?

**Review by michaelstaib — APPROVED** [review]
The PR looks good to me now... @philbir can we merge?

Beto still needs to sign the CLA.

**Review by Carael — APPROVED** [review]
Looks good, approved.

**Pull request merged**
