### PR TITLE
Update Nats.Tests to use AlterNats 1.0.6 (osx socket issue)

### PR DESCRIPTION
**Pull request by oising**
update alternats to 1.0.6 (fix osx socket issue)

### CODE REVIEW

**Comment by glucaci** [comment]
Thanks! Will be released with 0.18.0-preview.4

**Comment by oising** [comment]
@glucaci You released preview.4 but nothing in nuget yet?

**Comment by glucaci** [comment]
Just fixed it and released with [preview.6](https://www.nuget.org/packages/Squadron.Nats/0.18.0-preview.6)

**Pull request merged**
