### PR TITLE
Helper methods for receiving a message

### PR DESCRIPTION
**Pull request by Sondergaard**
When waiting for a message to be received on a SubscriptionClient the logic can get complicated and redundant.

The class SubscriptionClientExtensions provides some convient methods that can be used to await and deserialize a message to a concrete DTO.

The inner workings are based on TaskCompletionSource<T> as shown in the examples on the website. Besides that a timeout options is added.

### CODE REVIEW

**Comment by glucaci** [comment]
Looks good !
Can you take a look on build please?!

**Comment by Sondergaard** [comment]
Hi @glucaci 

I was able to reproduce on my local development setup.

For some reason the nuget reference was not included.
The branch is updated with the missing package and is now working as expected.

Can you have another go?

**Comment by Sondergaard** [comment]
HI @glucaci 

It appears that the reference docker images, microsoft/mssql-server-linux:latest, is removed from docker-hub. When I perform a pull of the image I get the following error.

``` text
> docker pull microsoft/mssql-server-linux:latest
Error response from daemon: manifest for microsoft/mssql-server-linux:latest not found: manifest unknown: manifest unknown
```

**Pull request merged**
