### PR TITLE
Allow multiple ports per container

### PR DESCRIPTION
**Pull request by fredericbirke**
I added the possibility to expose more than only one port on a container.
To not break the API, the container resources now have a "main port", which is the port that is set using `.InternalPort()`, `.ExternalPort` on th eContainerResourceBuilder.

Additional Ports can be registered using the `.AddPortMapping()` method on the builder. You can either let the OS assign an external port for an internal port, or you can set an external static port, as with the main port.

The main Ports are also exposed on the `ContainerResource.Instance.AdditionalPorts`, so that one can find out, what external port an additional port was assigned to, after the container has started.

I added a test case for checking if everything is working as expected, but i needed to build an own small image, because I didn't find anything suitable for the test.
The image can be found here:
https://hub.docker.com/repository/docker/fredericbirke/test-image
The source of the image can be found here:
https://github.com/fredericbirke/docker-test-image

### CODE REVIEW

**Comment by glucaci** [comment]
Hi @fredericbirke thanks for your contribution!
It seams that the test is failing. It works locally ?

**Comment by fredericbirke** [comment]
The test is flaky, which I didn't notice on my local machine. I'll check it out today and see if I can fix the error.

**Comment by fredericbirke** [comment]
I fixed the flaky test. @glucaci  can you try to rerun the pipleline?

**Review by philbir — APPROVED** [review]

**Pull request merged**
